enum Category {
  BREAKFAST = "BREAKFAST",
  LUNCH = "LUNCH",
  DINNER = "DINNER",
  DESSERT = "DESSERT",
  SNACK = "SNACK",
}

export const recipes = [
  {
    id: "1",
    title: "Homemade Margherita Pizza",
    description:
      "A classic Italian pizza featuring a crispy thin crust topped with fresh mozzarella, ripe tomatoes, and aromatic basil leaves. This recipe captures the essence of traditional Neapolitan pizza-making.",
    makeTime: 45,
    ingredients: [
      "2 1/4 cups all-purpose flour",
      "1 tsp salt",
      "1 tsp sugar",
      "1 packet active dry yeast",
      "3/4 cup warm water",
      "2 tbsp olive oil",
      "1 cup crushed tomatoes",
      "8 oz fresh mozzarella cheese",
      "Fresh basil leaves",
      "2 cloves garlic, minced",
      "Salt and pepper to taste",
    ],
    steps: [
      "In a large bowl, combine warm water, sugar, and yeast. Let stand for 5 minutes until foamy.",
      "Add flour, salt, and olive oil to the yeast mixture. Mix until a dough forms.",
      "Knead the dough on a floured surface for about 8-10 minutes until smooth and elastic.",
      "Place dough in a greased bowl, cover with a damp cloth, and let rise in a warm place for 1 hour.",
      "Preheat your oven to 475°F (245°C). If you have a pizza stone, place it in the oven to heat.",
      "Punch down the dough and roll it out on a floured surface to your desired thickness.",
      "Transfer the dough to a pizza pan or peel. Spread crushed tomatoes evenly over the surface.",
      "Add minced garlic, then tear the mozzarella and distribute it over the pizza.",
      "Season with salt and pepper. Drizzle with a little olive oil.",
      "Bake for 12-15 minutes until the crust is golden and the cheese is bubbly.",
      "Remove from oven, top with fresh basil leaves, slice, and serve immediately.",
    ],
    tips: "For the best results, use a pizza stone and preheat it for at least 30 minutes. The high heat creates a crispy crust. You can also use bread flour instead of all-purpose for a chewier texture. Fresh mozzarella works best - drain it well to avoid a soggy pizza.",
    category: Category.DINNER,
    imageUrl:
      "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=1200&q=80",
    author: { id: "1", name: "Chef Mario Rossi" },
    authorId: "1",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    title: "Classic Spaghetti Carbonara",
    description:
      "A rich and creamy Italian pasta made with eggs, pecorino cheese, crispy pancetta, and black pepper. Simple ingredients with bold flavors.",
    makeTime: 30,
    ingredients: [
      "400g spaghetti",
      "150g pancetta",
      "3 large eggs",
      "1 cup grated pecorino cheese",
      "2 cloves garlic",
      "Salt to taste",
      "Freshly ground black pepper",
    ],
    steps: [
      "Boil spaghetti in salted water until al dente.",
      "Cook pancetta with garlic until crispy.",
      "Whisk eggs, cheese, and black pepper in a bowl.",
      "Drain pasta and combine with pancetta.",
      "Remove from heat and quickly mix in egg mixture.",
      "Serve immediately with extra cheese.",
    ],
    tips: "Do not add eggs over heat or they will scramble.",
    category: Category.DINNER,
    imageUrl:
      "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=1200&q=80",
    author: { id: "2", name: "Chef Luca Romano" },
    authorId: "2",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "3",
    title: "Chicken Fried Rice",
    description:
      "A quick and flavorful Asian-style fried rice with chicken, eggs, and vegetables.",
    makeTime: 25,
    ingredients: [
      "2 cups cooked rice",
      "200g chicken breast",
      "2 eggs",
      "1 cup mixed vegetables",
      "2 tbsp soy sauce",
      "1 tbsp sesame oil",
      "Salt and pepper",
    ],
    steps: [
      "Heat oil in a pan and cook chicken until done.",
      "Add vegetables and stir-fry for 2 minutes.",
      "Push ingredients aside and scramble eggs.",
      "Add rice and soy sauce.",
      "Stir well and cook for 5 minutes.",
    ],
    tips: "Use cold rice for best texture.",
    category: Category.LUNCH,
    imageUrl:
      "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=1200&q=80",
    author: { id: "3", name: "Chef Lin Wei" },
    authorId: "3",
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-05"),
  },
  {
    id: "4",
    title: "Avocado Toast",
    description:
      "A healthy breakfast made with creamy avocado on crispy toasted bread.",
    makeTime: 10,
    ingredients: [
      "2 slices bread",
      "1 ripe avocado",
      "Salt and pepper",
      "Chili flakes",
      "Olive oil",
    ],
    steps: [
      "Toast the bread slices.",
      "Mash avocado with salt and pepper.",
      "Spread avocado on toast.",
      "Drizzle olive oil and sprinkle chili flakes.",
    ],
    tips: "Add a poached egg for extra protein.",
    category: Category.BREAKFAST,
    imageUrl:
      "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=1200&q=80",
    author: { id: "4", name: "Chef Emma Green" },
    authorId: "4",
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
  },
  {
    id: "5",
    title: "Juicy Beef Burger",
    description:
      "A classic beef burger with a juicy patty, fresh veggies, and soft buns.",
    makeTime: 35,
    ingredients: [
      "500g ground beef",
      "Burger buns",
      "Cheese slices",
      "Lettuce",
      "Tomato",
      "Onion",
      "Salt and pepper",
    ],
    steps: [
      "Season beef and form patties.",
      "Grill patties until cooked.",
      "Toast buns lightly.",
      "Assemble burger with toppings.",
    ],
    tips: "Do not over-press the patty while cooking.",
    category: Category.DINNER,
    imageUrl:
      "https://images.unsplash.com/photo-1550547660-d9450f859349?w=1200&q=80",
    author: { id: "5", name: "Chef John Miller" },
    authorId: "5",
    createdAt: new Date("2024-02-12"),
    updatedAt: new Date("2024-02-12"),
  },
  {
    id: "6",
    title: "Vegetable Stir Fry",
    description:
      "A colorful and healthy mix of stir-fried vegetables in a light soy sauce.",
    makeTime: 20,
    ingredients: [
      "Broccoli",
      "Carrots",
      "Bell peppers",
      "Soy sauce",
      "Garlic",
      "Sesame oil",
    ],
    steps: [
      "Heat oil in a wok.",
      "Add garlic and stir-fry briefly.",
      "Add vegetables and cook on high heat.",
      "Add soy sauce and toss well.",
    ],
    tips: "Cook on high heat to keep vegetables crisp.",
    category: Category.LUNCH,
    imageUrl:
      "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=1200&q=80",
    author: { id: "6", name: "Chef Mei Wong" },
    authorId: "6",
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
  },
  {
    id: "7",
    title: "Fluffy Pancakes",
    description: "Soft and fluffy pancakes perfect for a sweet breakfast.",
    makeTime: 20,
    ingredients: [
      "1 cup flour",
      "1 tbsp sugar",
      "1 tsp baking powder",
      "1 egg",
      "1 cup milk",
      "Butter",
    ],
    steps: [
      "Mix dry ingredients.",
      "Add egg and milk.",
      "Cook batter on hot pan.",
      "Flip and cook until golden.",
    ],
    tips: "Do not overmix the batter.",
    category: Category.BREAKFAST,
    imageUrl:
      "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=1200&q=80",
    author: { id: "7", name: "Chef Anna Lee" },
    authorId: "7",
    createdAt: new Date("2024-02-18"),
    updatedAt: new Date("2024-02-18"),
  },
  {
    id: "8",
    title: "Caesar Salad",
    description:
      "A refreshing salad with crunchy croutons and creamy Caesar dressing.",
    makeTime: 15,
    ingredients: [
      "Romaine lettuce",
      "Croutons",
      "Parmesan cheese",
      "Caesar dressing",
    ],
    steps: [
      "Wash and chop lettuce.",
      "Add croutons and cheese.",
      "Toss with dressing.",
    ],
    tips: "Add grilled chicken for extra protein.",
    category: Category.LUNCH,
    imageUrl:
      "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=1200&q=80",
    author: { id: "8", name: "Chef Olivia Brown" },
    authorId: "8",
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "9",
    title: "Chocolate Brownies",
    description: "Rich and fudgy chocolate brownies with a crackly top.",
    makeTime: 40,
    ingredients: [
      "Dark chocolate",
      "Butter",
      "Sugar",
      "Eggs",
      "Flour",
      "Cocoa powder",
    ],
    steps: [
      "Melt chocolate and butter.",
      "Mix sugar and eggs.",
      "Combine all ingredients.",
      "Bake at 180°C for 25 minutes.",
    ],
    tips: "Do not overbake for fudgy brownies.",
    category: Category.DESSERT,
    imageUrl:
      "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=1200&q=80",
    author: { id: "9", name: "Chef Noah Smith" },
    authorId: "9",
    createdAt: new Date("2024-02-22"),
    updatedAt: new Date("2024-02-22"),
  },
  {
    id: "10",
    title: "Grilled Salmon",
    description: "Perfectly grilled salmon with lemon and herbs.",
    makeTime: 25,
    ingredients: [
      "Salmon fillets",
      "Lemon",
      "Olive oil",
      "Garlic",
      "Salt and pepper",
    ],
    steps: [
      "Season salmon with salt and pepper.",
      "Grill skin-side down.",
      "Flip and cook until done.",
      "Serve with lemon.",
    ],
    tips: "Do not overcook salmon.",
    category: Category.DINNER,
    imageUrl:
      "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=1200&q=80",
    author: { id: "10", name: "Chef Daniel King" },
    authorId: "10",
    createdAt: new Date("2024-02-25"),
    updatedAt: new Date("2024-02-25"),
  },
];
